### ISSUE TITLE
可以增加关键字的数量吗?

### ISSUE THREAD

**Issue by xiekecheng** [hfc1994/IgnoreSomeCompanies#1]
可以增加关键字的数量吗,最大只支持32个关键字.....不够用,太多培训公司了不够屏蔽
关键字限定数量为32，此刻关键字数量已达上限，可点击关键字进行删减

**Comment by hfc1994** [comment]
真抱歉，今天才看到你的issue...这是个小改动，已经更改限制到128个了，你可以通过油猴更新到1.1.1版本。现在想想，32个确实略小了，哈哈。

最后感谢你的建议\(^o^)/~
